language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install -y libudev-dev
  - mv travis_secrets.yaml secrets.yaml
  - touch ssl_key.pem ssl_cert.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config

