homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include config/customize.yaml
  packages: !include_dir_named packages

lovelace:
  mode: yaml

updater:
  include_used_components: true

custom_updater:
  track:
    - cards
    - components

duckdns:
  domain: kruiwagen
  access_token: !secret duckdns_accesstoken

http:
  base_url: !secret base_url
  trusted_networks: !secret trusted_networks
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  api_password: !secret http_password

frontend:
config:
history:
logbook:
discovery:
ios:
sun:

zwave: !include config/zwave.yaml
recorder: !include config/recorder.yaml

influxdb: !include config/influxdb.yaml

# TODO: hieronder moet nog weg
python_script:

