homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: trusted_networks
      trusted_networks: !secret trusted_networks
    - type: legacy_api_password
      api_password: !secret http_password
    - type: homeassistant

lovelace_gen:
lovelace:
  mode: yaml

updater:
  include_used_components: true

custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/peternijssen/lovelace-postnl/master/tracker.json

duckdns:
  domain: kruiwagen
  access_token: !secret duckdns_accesstoken

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

notify:
  - platform: group
    name: floris_en_marijke
    services:
      - service: ios_iphone_van_floris
      - service: ios_marijkes_iphone

sensor:
  - platform: time_date
    display_options:
      - 'date'
      - 'date_time'

frontend:
config:
history:
logbook:
discovery:
ios:
sun:
system_health:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml
  device_config_glob:
    "sensor.*_sourcenodeid*":
      ignored: true
    "sensor.*_exporting*":
      ignored: true

recorder: !include config/recorder.yaml

influxdb: !include config/influxdb.yaml

# TODO: hieronder moet nog weg
python_script:

