title: Bleekweg 28

resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /local/card-tools.js?v=deb8e3
    type: js
  - url: /local/monster-card.js?v=0.2.3
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/popup-card.js?v=044b08
    type: js
  - url: /local/tracker-card.js?v=1.2.3
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/lovelace-postnl-card/postnl-card.js
    type: module

cch:
  hide_config: true

views:
  - !include lovelace/home.yaml
  - !include lovelace/afval.yaml
  - !include lovelace/omgeving.yaml
  - !include lovelace/climate.yaml
  - !include lovelace/verlichting.yaml
  - !include lovelace/post.yaml
  - !include lovelace/system.yaml
  - !include lovelace/all_entities.yaml 
