title: Bleekweg 28

resources:
  - url: /local/monster-card.js?v=1
    type: js

views:
  - title: System
    icon: mdi:settings
    cards:
      - type: glance
        title: Raspberry Pi
        entities:
          - sensor.disk_use_percent_
          - sensor.processor_use
          - sensor.memory_use_percent
      - type: custom:monster-card
        show_empty: true
        card: 
          type: glance
          title: Tracker
        filter:
          include:
            - domain: device_tracker
              state: 'home'

  - title: Example
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: weather-forecast
        entity: weather.enschede
      - type: picture-entity
        entity: camera.buienradar
        show_state: false
        show_name: false
      - type: conditional
        conditions:
          - entity: sensor.postnl
            state_not: "0"
        card:
          type: entities
          title: PostNL
          entities:
            - sensor.postnl
      - type: entity-filter
        entities:
          - device_tracker.iphone_van_floris
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: switch.woonkamer_staandelamp

  - icon: mdi:home-assistant
    title: Second view
    cards:
      - type: entities
        title: Example
        entities:
          - switch.woonkamer_staandelamp
          - switch.woonkamer_tv_backlight
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
