title: Bleekweg 28

resources:
  - url: /local/card-tools.js?v=deb8e3
    type: js
  - url: /local/monster-card.js?v=0.2.3
    type: js
  - url: /local/slider-entity-row.js?v=be80ff
    type: js
  - url: /local/popup-card.js?v=044b08
    type: js
  - url: /local/tracker-card.js?v=1.2.3
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.7.0
    type: module
  - url: /local/simple-thermostat.js?v=0.25.0
    type: module

views:
  - !include lovelace/home.yaml
  - !include lovelace/climate.yaml
  - !include lovelace/afval.yaml
  - !include lovelace/verlichting.yaml
  - !include lovelace/omgeving.yaml
  - !include lovelace/system.yaml
  - !include lovelace/all_entities.yaml 
