title: Bleekweg 28

resources:
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/gauge-card.js?v=1
    type: js

views:
  - title: Home
    icon: mdi:home
    cards:
      - type: entities
        title: Verlichting
        entities: 
          - light.keuken
          - light.woonkamer
      - type: entities
        title: Muziekkamer
        entities:
          - sensor.muziekkamer_relative_humidity
          - sensor.muziekkamer_temperature
      - type: entities
        title: Wasmachine
        entities:
          - sensor.wasmachine_status
          - sensor.wasmachine_power

  - title: System
    icon: mdi:settings
    cards:
      - type: glance
        title: Raspberry Pi
        entities:
          - sensor.disk_use_percent_
          - sensor.processor_use
          - sensor.memory_use_percent
      - type: entities
        title: Batterijen
        entities:
          - sensor.muziekkamer_multisensor_battery
          - sensor.iphone_van_floris_battery_level
      - type: custom:monster-card
        show_empty: true
        card: 
          type: glance
          title: Tracker
        filter:
          include:
            - domain: device_tracker
              #state: 'home'

  - title: Example
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: weather-forecast
        entity: weather.enschede
      - type: picture-entity
        entity: camera.buienradar
        show_state: false
        show_name: false
      - type: custom:gauge-card
        title: Enschede
        entity: sensor.enschede_temperatuur
        min: -20
        max: 35
      - type: conditional
        conditions:
          - entity: sensor.postnl
            state_not: "0"
        card:
          type: entities
          title: PostNL
          entities:
            - sensor.postnl
      - type: entity-filter
        entities:
          - device_tracker.iphone_van_floris
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

  - icon: mdi:home-assistant
    title: Second view
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: All Lights
        filter:
          include:
            - domain: light
      - type: custom:monster-card
        card:
          type: entities
          title: Power Consumption
        filter:
          include:
            - entity_id: "*power"
      - type: custom:monster-card
        card:
          type: entities
          title: All Sensors
        filter:
          include:
            - domain: sensor
