- platform: template
  sensors:
    muziekkamer_multisensor_battery:
      friendly_name: Muziekkamer Multisensor
      unit_of_measurement: "%"
      device_class: battery
      value_template: "{{ states.zwave.muziekkamer_multisensor_2in1.attributes.battery_level }}"

