- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: swap_use_percent
    - type: swap_use_percent
    - type: disk_use_percent
      arg: /
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: ipv4_address
      arg: wlan0
    - type: process
      arg: hass
    - type: process
      arg: grafana-server
    - type: process
      arg: influxd
    - type: process
      arg: sshd
