- alias: 'Start HomeKit'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
  action:
    - service: homekit.start
    - service: notify.ios_iphone_van_floris
      data:
        message: "HomeKit started"

