- id: mini_1_pressed
  alias: 'Minimote Button 1 Pressed'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.minimote
        scene_id: 1
  action:
    - service: homeassistant.turn_on
      entity_id: light.woonkamer

#- id: mini_1_held
#  alias: 'Minimote Button 1 Held'
#  trigger:
#    - platform: event
#      event_type: zwave.scene_activated
#      event_data:
#        entity_id: zwave.minimote
#        scene_id: 2
#  action:
#    - service: homeassistant.turn_off
#      entity_id: switch.woonkamer_staandelamp

- id: mini_2_pressed
  alias: 'Minimote Button 2 Pressed'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.minimote
        scene_id: 3
  action:
    - service: homeassistant.turn_off
      entity_id: light.woonkamer

#- id: mini_2_held
#  alias: 'Minimote Button 2 Held'
#  trigger:
#    - platform: event
#      event_type: zwave.scene_activated
#      event_data:
#        entity_id: zwave.minimote
#        scene_id: 4
#  action:
#    - service: homeassistant.turn_off
#      entity_id: switch.woonkamer_tv_backlight

- id: mini_3_pressed
  alias: 'Minimote Button 3 Pressed'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.minimote
        scene_id: 5
  action:
    - service: homeassistant.turn_on
      entity_id: light.keuken

#- id: mini_3_held
#  alias: 'Minimote Button 3 Held'
#  trigger:
#    - platform: event
#      event_type: zwave.scene_activated
#      event_data:
#        entity_id: zwave.minimote
#        scene_id: 6
#  action:
#    - service: homeassistant.turn_off
#      entity_id: group.keuken

- id: mini_4_pressed
  alias: 'Minimote Button 4 Pressed'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.minimote
        scene_id: 7
  action:
    - service: homeassistant.turn_off
      entity_id: light.keuken

#- id: mini_4_held
#  alias: 'Minimote Button 4 Held'
#  trigger:
#    - platform: event
#      event_type: zwave.scene_activated
#      event_data:
#        entity_id: zwave.minimote
#        scene_id: 8
#  action:
#    - service: notify.ios_iphone_van_floris
#      data:
#        message: "Button 4 Held"


