group.all_automations:
  hidden: false
group.all_devices:
  hidden: false
group.all_lights:
  hidden: false
group.all_scripts:
  hidden: false
group.all_switches:
  hidden: false
zone.home:
  radius: 50
switch.keuken_kookplaat_spotjes:
  hidden: true
switch.woonkamer_staandelamp:
  hidden: true
switch.woonkamer_tv_backlight:
  hidden: true
sensor.wasmachine_status:
  icon: mdi:washing-machine
sensor.muziekkamer_relative_humidity:
  device_class: humidity
light.woonkamer_staandelamp:
  icon: mdi:floor-lamp
light.woonkamer_tv_backlight:
  icon: mdi:television-classic
light.keuken_kookplaat_spotjes:
  icon: mdi:stove
light.keuken_raam_spotjes:
  icon: mdi:water-pump
