host: 127.0.0.1
database: home
default_measurement: state
include:
  entities:
    - sensor.enschede_temperatuur
    - sensor.muziekkamer_temperature
    - sensor.woonkamer_multisensor_temperature
    - sensor.muziekkamer_relative_humidity
    - sensor.woonkamer_multisensor_relative_humidity
    - sensor.wasmachine_power
    - sensor.wasmachine_status
    - sensor.memory_use_percent
