usb_path: /dev/ttyACM0
network_key: !secret zwave_network_key
device_config: !include ../zwave_device_config.yaml
device_config_glob:
  "sensor.*_sourcenodeid*":
    ignored: true
  "sensor.*_exporting*":
    ignored: true

