- platform: template
  lights: 
    keuken_kookplaat_spotjes:
      value_template: '{{ is_state("switch.keuken_kookplaat_spotjes", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.keuken_kookplaat_spotjes
      turn_off:
        service: switch.turn_off
        entity_id: switch.keuken_kookplaat_spotjes

- platform: group
  name: Keuken
  entities:
    - light.keuken_raam_spotjes
    - light.keuken_kookplaat_spotjes
