- platform: template
  lights:
    woonkamer_tv_backlight:
      value_template: '{{ is_state("switch.woonkamer_tv_backlight", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.woonkamer_tv_backlight
      turn_off:
        service: switch.turn_off
        entity_id: switch.woonkamer_tv_backlight
    woonkamer_staandelamp:
      value_template: '{{ is_state("switch.woonkamer_staandelamp", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.woonkamer_staandelamp
      turn_off:
        service: switch.turn_off
        entity_id: switch.woonkamer_staandelamp

- platform: group
  name: Woonkamer
  entities:
    - light.woonkamer_staandelamp
    - light.woonkamer_tv_backlight
