homeassistant:
  customize:
    switch.harmony_poweroff:
      icon: mdi:power
    switch.harmony_watchtv:
      icon: mdi:television
    switch.harmony_listenradio:
      icon: mdi:radio
    switch.harmony_playwii:
      icon: mdi:gamepad-variant-outline
    switch.harmony_appletv:
      icon: mdi:television-play

remote:
  - platform: harmony
    name: Harmony Hub
    activity: Watch TV

sensor:
  - platform: template
    sensors:
      harmony_activity:
        value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') }}"
        friendly_name: 'Activiteit'

emulated_hue:
  exposed_domains:
    - light

script:
  harmony_volume_up:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: '65641783'
          command: 'VolumeUp'
  harmony_volume_down:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: '65641783'
          command: 'VolumeDown'
  harmony_volume_mute:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: '65641783'
          command: 'Mute'

switch:
  - platform: template
    switches:
      harmony_watchtv:
        friendly_name: 'TV'
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.harmony_hub
          data:
            activity: "41553884"
        turn_off:
          service: remote.turn_off
          entity_id: remote.harmony_hub
      harmony_listenradio:
        friendly_name: 'Radio'
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Radio') }}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.harmony_hub
          data:
            activity: "41553885"
        turn_off:
          service: remote.turn_off
          entity_id: remote.harmony_hub
      harmony_playwii:
        friendly_name: 'Wii'
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Wii') }}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.harmony_hub
          data:
            activity: "41553886"
        turn_off:
          service: remote.turn_off
          entity_id: remote.harmony_hub
      harmony_appletv:
        friendly_name: 'Apple TV'
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Apple TV') }}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.harmony_hub
          data:
            activity: "41553888"
        turn_off:
          service: remote.turn_off
          entity_id: remote.harmony_hub
      harmony_poweroff:
        friendly_name: 'Uit'
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
        turn_on:
          service: remote.turn_off
          entity_id: remote.harmony_hub
        turn_off:
          service: remote.turn_off
          entity_id: remote.harmony_hub
