homeassistant:
  customize:
    sensor.twentemilieu_groente_fruit_en_tuinafval:
      entity_picture: /local/icons/gft3.png
    sensor.twentemilieu_papier_en_karton:
      entity_picture: /local/icons/papier3.png
    sensor.twentemilieu_pmd:
      entity_picture: /local/icons/plastic3.png
    sensor.twentemilieu_restafval:
      entity_picture: /local/icons/rest3.png

sensor:
  - platform: twentemilieu
    postcode: 7512BZ
    housenumber: 28
    resources:
      - today
      - tomorrow
      - grey
      - green
      - paper
      - packages

input_boolean:
  notify_trash:
    name: Afval notificaties
    initial: on
    icon: mdi:recycle

automation:
  - alias: Afval vandaag
    initial_state: true
    trigger:
      - platform: time
        at: '7:00:00'
    condition:
      - condition: template
        value_template: >
          {{ is_state('input_boolean.notify_trash', 'on') }}
      - condition: template
        value_template: >
          {{ states('sensor.twentemilieu_vandaag') != 'Geen' }}
    action:
      - service: notify.floris_en_marijke
        data_template:
          title: Afval aan straat zetten
          message: >
            {% set weekdays = ["maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"] %}
            {% set months = ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"] %}
            {% set this_month = months[now().month-1] %}
            {{ states('sensor.twentemilieu_vandaag') }} wordt vandaag ({{now().day}} {{this_month}}) opgehaald!
          data:
            attachment:
              url: >
                {%- set icons = {'Geen': 'kliko3.png', 'PMD':'plastic3.png', 'Groente, fruit- en tuinafval':'gft3.png', 'Papier en karton':'papier3.png', 'Restafval':'rest3.png'} -%}
                https://kruiwagen.duckdns.org:8123/local/icons/{{icons[states('sensor.twentemilieu_vandaag')]}}
              content-type: png
              hide-thumbnail: false

  - alias: Afval morgen
    initial_state: true
    trigger:
      - platform: time
        at: '20:30:00'
    condition:
      - condition: template
        value_template: >
          {{ is_state('input_boolean.notify_trash', 'on') }}
      - condition: template
        value_template: >
          {{ states('sensor.twentemilieu_morgen') != 'Geen' }}
    action:
      - service: notify.floris_en_marijke 
        data_template:
          title: Afval aan straat zetten
          message: >
            {{ states('sensor.twentemilieu_morgen') }} wordt morgen opgehaald!
          data:
            attachment:
              url: >
                {%- set icons = {'Geen': 'kliko3.png', 'PMD':'plastic3.png', 'Groente, fruit- en tuinafval':'gft3.png', 'Papier en karton':'papier3.png', 'Restafval':'rest3.png'} -%}
                https://kruiwagen.duckdns.org:8123/local/icons/{{icons[states('sensor.twentemilieu_morgen')]}}
              content-type: png
              hide-thumbnail: false
