homeassistant:
  customize:
    sensor.twentemilieu_groente_fruit_en_tuinafval:
      entity_picture: /local/icons/gft3.png
    sensor.twentemilieu_papier_en_karton:
      entity_picture: /local/icons/papier3.png
    sensor.twentemilieu_pmd:
      entity_picture: /local/icons/plastic3.png
    sensor.twentemilieu_restafval:
      entity_picture: /local/icons/rest3.png

sensor:
  - platform: twentemilieu
    postcode: 7512BZ
    housenumber: 28
    resources:
      - today
      - tomorrow
      - grey
      - green
      - paper
      - packages

input_boolean:
  notify_trash:
    name: Afval notificaties
    initial: off
    icon: mdi:recycle

automation:
  - alias: Afval vandaag
    trigger:
      - platform: time
        at: '7:00:00'
    condition:
      - condition: template
        value_template: >
          {{ is_state('input_boolean.notify_trash', 'on') }}
      - condition: template
        value_template: >
          {{ states('sensor.twentemilieu_vandaag') != 'Geen' }}
    action:
      - service: notify.ios_iphone_van_floris
        data_template:
          title: Afval aan straat zetten
          message: >
            {{ states('sensor.twentemilieu_vandaag') }} wordt vandaag ({{now().strftime("%d %B")}}) opgehaald!

  - alias: Afval morgen
    trigger:
      - platform: time
        at: '20:30:00'
    condition:
      - condition: template
        value_template: >
          {{ is_state('input_boolean.notify_trash', 'on') }}
      - condition: template
        value_template: >
          {{ states('sensor.twentemilieu_morgen') != 'Geen' }}
    action:
      - service: notify.ios_iphone_van_floris
        data_template:
          title: Afval aan straat zetten
          message: >
            {{ states('sensor.twentemilieu_morgen') }} wordt morgen opgehaald!
