shell_command:
  z_wave_graph: /srv/homeassistant/bin/python3 ~/bin/z-wave-graph.py

automation:
  - alias: Generate Z-Wave graph
    trigger:
      platform: time
      minutes: '/5'
      seconds: 00
    action:
      - service: shell_command.z_wave_graph
